services:

  php_fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
      target: development
    container_name: php_fpm
    volumes:
      - ../app/:/var/www/html
      - ./php/conf.d:/usr/local/etc/php/conf.d/


  nginx: 
    image: nginx:1.25.3-alpine
    container_name: nginx
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 8080:8080
    volumes:
      - ../app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm


networks:
  default:
    name: dev
    external: true
